# imort numpy

In [55]:
import numpy as np

### np.array : convert py list to numpy array for easy calculations

In [56]:
arr01 = np.array([1, 2, 3, 4])
arr01

array([1, 2, 3, 4])

### .shape : show the shape of table

In [57]:
arr02 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr02.shape)

(2, 3)


### .ndim : show the number of dimensions

In [58]:
a = np.array([1, 2, 3])
print(a.ndim)

1


In [59]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.ndim)

2


### .dtype : show data type inside the array

In [60]:
c = np.array([69, 3.14])
print(c.dtype)

float64


In [61]:
print(a.dtype)

int64


### indexing / slicing

In [62]:
d = np.array([10, 20, 30, 40, 50])

print(d[0]) # first index
print(d[-1]) # last index
print(d[1:3]) # from 1 to 2 index being printed

10
50
[20 30]


In [63]:
e = np.array([[1, 2, 3], [4, 5, 6]])

print(e[0, 1])
print(e[1, :])

2
[4 5 6]


### axis : determines the direction of all calculations

In [64]:
f = np.array([[1, 2, 3],
              [4, 5, 6]])

print(f.sum()) # total
print(f.sum(axis= 0)) # total of columns
print(f.sum(axis= 1)) # total of rows

21
[5 7 9]
[ 6 15]


### .sum , .min/max , .std , .mean

In [65]:
data = np.array([10, 20, 30, 40, 50])

print(data.mean())
print(data.std())
print(data.min())
print(data.max())
print(data.sum())

30.0
14.142135623730951
10
50
150


In [66]:
g = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(g[1]) # second row
print(g[1].sum()) # total of second row
print(g[:, 1]) # second column
print(g[:, 1].sum()) # total of second column

[4 5 6]
15
[2 5 8]
15


In [67]:
h = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
print(h[:, 2]) # third column
print(h[:, 2].std()) # standard deviation of third column 
print(h[:, 2].mean()) # mean of third column
print(h[:, 2].max()) # show max of third column
print(h[:, 2].min()) # show min of third column

[ 3  7 11 15]
4.47213595499958
9.0
15
3


### create a 0 or 1 array

In [68]:

i = np.zeros(4)
j = np.ones((2 ,3))
print(i)
print(j)

[0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


### .arange : like range in python

In [69]:
k = np.arange(0, 10, 2)
k

array([0, 2, 4, 6, 8])

### .reshape : reshape array

In [70]:
l = np.arange(0, 6)
new_l = l.reshape(2, 3)
print(l) # 1 rows, 6 columns
print(new_l) # 2 row, 3 columns

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


### vectorized operations : much faster for loop

In [71]:
m = np.array([1, 2, 3, 4])
n = np.array([10, 20, 30, 40])

print(m + n) # index by index addition
print(m * 2) # multiplying each index by 2
print(m * n) # index by index multiplying

[11 22 33 44]
[2 4 6 8]
[ 10  40  90 160]


### boolean filtering

In [72]:
o = np.array([69, 6, 9, 7, 8, 26, 33, 85, 70])

mask = o > 20
print(mask)
print(o[mask]) # with var

print(o[o > 20]) # without var

[ True False False False False  True  True  True  True]
[69 26 33 85 70]
[69 26 33 85 70]


### nan : for mising data (nan : not a number)

In [73]:
p = np.array([1, 2, 3, np.nan, 4, 5])

print(np.isnan(p)) # for find mising data
print(np.nanmean(p)) # for mean without nan data

[False False False  True False False]
3.0


In [74]:
p.size

6

In [75]:
o.size

9